version: "2"

services:
  web:
    build: .
    command: "sh -c \"rm tmp/pids/server.pid ; yarn ; rails s -b 0.0.0.0\""
    ports:
      - 3000:3000
    tty: true
    stdin_open: true
    volumes:
      - .:/app
